[package]
name = "lsproj"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["yutadev31"]
repository = "https://github.com/yutadev31/lsproj"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.52", features = ["derive"] }
crossterm = "0.29.0"
git2 = "0.20.2"
